server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push # Adresse du conteneur Loki

scrape_configs:
- job_name: python_app
  static_configs:
  - targets:
      - localhost
    labels:
      job: digital_twin_logs
      __path__: /var/log/app_logs/*.log