global:
  scrape_interval: 15s # Je te conseille 15s pour le cloud, pour ne pas surcharger Azure

scrape_configs:
  - job_name: 'digital_twin_azure'
    scheme: https # Important car Azure utilise HTTPS
    metrics_path: '/metrics'
    static_configs:
      # On met ton URL Azure (sans le https:// ni les / à la fin)
      - targets: ['chiller-optimizer-tourki-a0eka5dvfahmbbfn.francecentral-01.azurewebsites.net']
